### ISSUE TITLE
Actually avoid hitting the DB

### ISSUE THREAD

**Issue by mlissner** [wimglenn/djangorestframework-queryfields#12]
I don't know if this is at all possible, but it'd be great if a `fields` request was actually more efficient due to not hitting the DB for a given field. We have some rather large fields, and while it's great not to have to serialize them, pulling them from the DB is a big job too. If we could avoid that too, it'd be huge.

**Comment by wimglenn** [comment]
I did actually look at this previously, and did not find an acceptable way.  The reason is that `QueryFields` is associated with a _serializer_, not with a _view_.  It is true that it works with `ModelSerializer` (and this is the typical use-case intended), but the `ModelSerializer` itself doesn't even access the db - in DRF, it gets passed a model instance, and uses plain old attribute lookup on the model instance.  

Note also that the code currently works with any plain old `Serializers` on apps that don't even have a database backend at all.  

The actual query that happens in DRF is not the responsibility of the serializer, but rather of the view (see [here](https://github.com/encode/django-rest-framework/blob/8f6173cd8afadd503dde124a616355ea80b5f6fe/rest_framework/generics.py#L73)).  So for `QueryFields` to influence the way data is pulled from the DB, it would have to 

- first determine if any fields were `ModelField` instances (easy).  
- introspect the view object somehow (probably possible but might involve black magic) 
- modify how the `get_queryset` method of the view works, dynamically, without breaking anything that DRF relies on internally (sounds fiendishly difficult)

This last part is the real deal-breaker, because all the DRF code assumes that there is a Django model instance, not an element of the `django.db.models.query.ValuesQuerySet` (which is what you would get from pulling only partial data from the db with Django ORM).  

In the end I decided this could not be the responsibility of `QueryFields`, and would be better suited as a feature request directly for DRF's `ModelSerializer`.

**Comment by mlissner** [comment]
Makes sense. I dug around in DRF looking for this feature request. I'm surprised not to see it. I imagine it would make a huge difference to a variety of implementations.

**Comment by mlissner** [comment]
Theoretical question after reading your post above: Why implement this as a mixin to the serializer instead of the view/viewset?

**Comment by wimglenn** [comment]
That's where the information is - consider for example a `SerializerMethodField` instance.  The view needn't know about this field at all, and the only way to access the field would be through the serializer anyway.  If working on the view we could perhaps drop fields in post-processing, but it violates this library's guarantee that unneeded fields are never serialized at all in the first place.

There are also many different kind of views, function based, class based, the DRF viewsets, and even dynamically auto-generated views - so a solution which works on the view could be pretty difficult to implement correctly.  It's just some callable returning a response object, but a serializer class is a much easier thing to nail down.

**Comment by mlissner** [comment]
Thanks for the explanation.
