### ISSUE TITLE
Add note to docs / github landing to mention supported Django/DRF/Python versions

### ISSUE THREAD

**Issue by melgart** [wimglenn/djangorestframework-queryfields#13]
hi there: 

sorry for such a trivial question, but does drf queryfields support DRF 3.x yet? I don't see any explicit mention of which versions you do or don't support in your docs. we're in the middle of migrating from DRF 2.x to 3.0.0 and were getting some exceptions, but it's not super clear yet if the problem is with our code (probable) or whether you just don't support 3.x yet. Again, sorry for such a simple question.

**Comment by wimglenn** [comment]
Yes, DRF3 is supported.

**Comment by melgart** [comment]
thanks for the reply. i was asking because your travis file only shows the testing environment being set up with DRF 2.4.x (https://github.com/wimglenn/djangorestframework-queryfields/blob/master/.travis.yml).

**Comment by wimglenn** [comment]
Hmm, I think you're reading that travis file incorrectly.  DRF 2.4.x is only installed when testing against Django 1.7 environment (since DRF 3 requires Django 1.8+).  All the other configurations use DRF current version, see for example [the latest build on Django 1.11 / Python 3.6](https://travis-ci.org/wimglenn/djangorestframework-queryfields/jobs/223318254): it has `djangorestframework==3.6.2` listed in the pip freeze.
