### ISSUE TITLE
Select fields in POST/PATCH requests

### ISSUE THREAD

**Issue by GasparPizarro** [wimglenn/djangorestframework-queryfields#14]
I have an APIView with get, post, and patch methods. and I am returning data through a QueryFieldsMixin-inherited serializer, passing the request as context, like this:

`[GET] return Response(ThingSerializer(analyses, many=True, context={'request': request}).data)`
`[POST] return Response(AnalysisSerializer(analysis, context={'request': request}).data, status=status.HTTP_201_CREATED)`
`[PATCH] return Response(AnalysisSerializer(analysis, context={'request': request}).data)`

However, the `fields=` and `fields!=` only work with the GET requests. In the other cases, the full object, which has a very heavy field that I must not return, is returned. Is this expected behavior?

**Comment by wimglenn** [comment]
Yes, that is [as designed](https://github.com/wimglenn/djangorestframework-queryfields/blob/3b3c2e78ae25906c3e4eb8ee1495bf8c3d105258/tests/test_userfields_with_plain_serializer.py#L133-L142).  

Since DRF uses a serializer on POST requests to deserialize and validate (when creating an instance), and it also uses a serializer to return a representation of the created instance, there would be ambiguity here on which serializer the fields should apply to.  Any effects for POST requests are explicitly disabled and `fields=` is ignored.  

If you have heavy fields you don't want serialized it might be better to exclude those all the time in the response to POST.  You can do that in DRF directly, we don't need queryfields for that.  But if the fields returned in a newly created instance need to be customized by the client on a per-request basis, then maybe I can extend queryfields to support this behaviour - please clarify the use case required?

**Comment by GasparPizarro** [comment]
@wimglenn I know it's

**Comment by GasparPizarro** [comment]
I'm gonna go with the `serializer.fields.pop` approach now. Thanks.
