### ISSUE TITLE
Documentation on test is missing

### ISSUE THREAD

**Issue by gustabot42** [wimglenn/djangorestframework-queryfields#24]
dev requirements:
``` bash
pip install mock_django
```

`manage.py`:
``` python
#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "test_settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```

**Comment by wimglenn** [comment]
Nope, writing a `manage.py` is not needed, because I use [`pytest-django`](https://pytest-django.readthedocs.io/en/latest/) plugin.  Other dev requirements (including the `mock_django`) are listed in a setuptools extra, [here](https://github.com/wimglenn/djangorestframework-queryfields/blob/b0aed3eb51625b20d187aa2ca1ec5a2982b979e2/setup.py#L28-L32). So, the correct way is simply:

    pip install --editable ".[dev]"
    pytest

I've now added some dev instructions onto the landing page in https://github.com/wimglenn/djangorestframework-queryfields/commit/b0aed3eb51625b20d187aa2ca1ec5a2982b979e2
